# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'THEm' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'FirebaseUI'
  pod 'Firebase/Auth'
  # Pods for THEm

  target 'THEmTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'THEmUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
